name: Deploy

on:
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: []

    steps:
    - name: Download backend artifact
      uses: actions/download-artifact@v4
      with:
        name: backend-binary
        path: backend

    - name: Download frontend artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-dist
        path: frontend/dist

    # Add your deployment steps here
    # Example for AWS deployment:
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1

    # - name: Deploy to AWS
    #   run: |
    #     # Add your deployment commands here
    #     echo "Deploying to production..." 